const CAMPUS_INFO = {
  campus1: {
    label:   'MAIN CAMPUS 1',
    address: 'Kagawasan Avenue, Dumaguete City',
    img:     'assets/campus1.jpg',
  },
  campus2: {
    label:   'MAIN CAMPUS 2',
    address: 'Brgy. Bajumpandan, Dumaguete City',
    img:     'assets/campus2.jpg',
  },
};

// pos: [x%, y%] — percentage of map image width/height
const BUILDINGS = {
  campus1: [
    { id:'gate1',          name:'Gate 1',                                    pos:[52, 4],  neighbors:['cas','info-tech','cba-cthm-upper'] },
    { id:'gate2',          name:'Gate 2',                                    pos:[92, 36], neighbors:['admin','mx','st','grad-school'] },
    { id:'gate3',          name:'Gate 3',                                    pos:[82, 97], neighbors:['cted','law'] },
    { id:'gate4',          name:'Gate 4',                                    pos:[22, 4],  neighbors:['cba-cthm-upper','commission'] },
    { id:'commission',     name:'Commission on Elections / CHED-NIR',        pos:[8,  18], neighbors:['gate4','cba-cthm-left'] },
    { id:'cba-cthm-upper', name:'CBA & CTHM Building (Upper)',               pos:[34, 12], neighbors:['gate4','gate1','info-tech','cba-cthm-left'] },
    { id:'info-tech',      name:'Info. Tech. Building',                      pos:[50, 12], neighbors:['gate1','cba-cthm-upper','cas','cultural-sports'] },
    { id:'cas',            name:'CAS Building',                              pos:[72, 12], neighbors:['gate1','info-tech','cr2','mechanical','mx','multi-tissue'] },
    { id:'cba-cthm-left',  name:'CBA & CTHM Building (Left)',                pos:[8,  34], neighbors:['commission','cba-cthm-upper','cnpahs'] },
    { id:'cr3',            name:'CR 3',                                      pos:[30, 26], neighbors:['cba-cthm-upper','cultural-sports'] },
    { id:'cultural-sports',name:'NORSU Cultural & Sports Complex',           pos:[48, 28], neighbors:['info-tech','cr3','cr2','pe'] },
    { id:'cr2',            name:'CR 2',                                      pos:[62, 24], neighbors:['cas','cultural-sports','open-court'] },
    { id:'open-court',     name:'Open Court',                                pos:[68, 32], neighbors:['cr2','mechanical','automotive','cr1'] },
    { id:'multi-tissue',   name:'Multi-Tissue Culture Laboratory',           pos:[82, 22], neighbors:['cas','mechanical'] },
    { id:'mechanical',     name:'Mechanical Building',                       pos:[82, 30], neighbors:['cas','multi-tissue','mx','open-court'] },
    { id:'mx',             name:'MX Building',                               pos:[88, 26], neighbors:['mechanical','admin','gate2','grad-school'] },
    { id:'admin',          name:'Admin Building',                            pos:[94, 20], neighbors:['gate2','mx'] },
    { id:'cnpahs',         name:'CNPAHS Building',                           pos:[20, 44], neighbors:['cba-cthm-left','pe'] },
    { id:'pe',             name:'P.E. Building',                             pos:[46, 44], neighbors:['cnpahs','cultural-sports','automotive'] },
    { id:'automotive',     name:'Automotive Building',                       pos:[62, 44], neighbors:['pe','open-court','cr1','canteen'] },
    { id:'cr1',            name:'CR 1',                                      pos:[74, 44], neighbors:['open-court','automotive','grad-school','canteen'] },
    { id:'grad-school',    name:'Graduate School Building',                  pos:[90, 44], neighbors:['gate2','mx','cr1','st'] },
    { id:'st',             name:'ST Building',                               pos:[92, 55], neighbors:['gate2','grad-school','cit-building'] },
    { id:'canteen',        name:'Canteen',                                   pos:[74, 54], neighbors:['automotive','cr1','supply-office','cit-building'] },
    { id:'supply-office',  name:'Supply Office',                             pos:[68, 62], neighbors:['canteen','sao','cit-open-court'] },
    { id:'cit-open-court', name:'CIT Open Court',                            pos:[76, 62], neighbors:['supply-office','cit-building','student-lounge'] },
    { id:'cit-building',   name:'CIT Building',                              pos:[84, 60], neighbors:['canteen','st','cit-open-court','sao'] },
    { id:'student-lounge', name:'Student Lounge',                            pos:[76, 70], neighbors:['cit-open-court','sao','cted-lounge'] },
    { id:'sao',            name:'SAO Building',                              pos:[68, 72], neighbors:['supply-office','cit-building','student-lounge','care-center'] },
    { id:'care-center',    name:'Care Center',                               pos:[68, 82], neighbors:['sao','cted','cted-lounge'] },
    { id:'cted-lounge',    name:'CTED Student Lounge',                       pos:[76, 80], neighbors:['student-lounge','care-center','cted'] },
    { id:'cted',           name:'CTED Building',                             pos:[72, 92], neighbors:['care-center','cted-lounge','gate3','law'] },
    { id:'law',            name:'Law Building',                              pos:[84, 90], neighbors:['cted','gate3'] },
  ],

  campus2: [
    { id:'main-gate',     name:'Main Gate',                                  pos:[36, 96], neighbors:['guardhouse','open-field'] },
    { id:'guardhouse',    name:'Guard House',                                pos:[28, 90], neighbors:['main-gate','cea'] },
    { id:'ccje-a',        name:'CCJE Building',                              pos:[16, 18], neighbors:['canteen','ccje-b'] },
    { id:'ccje-b',        name:'CCJE Building (2nd)',                        pos:[16, 42], neighbors:['ccje-a','mechanical','aviation'] },
    { id:'mechanical',    name:'Mechanical Engineering Building',            pos:[16, 62], neighbors:['ccje-b','cea','aviation'] },
    { id:'cea',           name:'CEA Building',                               pos:[16, 80], neighbors:['mechanical','guardhouse'] },
    { id:'canteen',       name:'Canteen',                                    pos:[34, 12], neighbors:['ccje-a','cit','aviation'] },
    { id:'cit',           name:'CIT Building',                               pos:[58, 10], neighbors:['canteen','maritime','aviation'] },
    { id:'maritime',      name:'Old Maritime Building',                      pos:[80, 10], neighbors:['cit','sts'] },
    { id:'aviation',      name:'CCJE/P.E./Aviation Building',                pos:[55, 42], neighbors:['canteen','cit','ccje-b','mechanical','aviation-area','sts'] },
    { id:'aviation-area', name:'Aviation Working Area',                      pos:[60, 64], neighbors:['aviation','stage','open-field'] },
    { id:'sts',           name:'STS Building',                               pos:[82, 52], neighbors:['maritime','aviation'] },
    { id:'stage',         name:'Stage',                                      pos:[52, 76], neighbors:['aviation-area','open-field'] },
    { id:'open-field',    name:'Open Field',                                 pos:[52, 86], neighbors:['stage','aviation-area','main-gate'] },
  ],
};